apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdmonedas-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostsPath:
    path: "/data/postgres"
  PersistentVolumeReclaimPolicy: Delete
  
