apiVersion: v1
kind: StatefulSet
metadata:
  name: bdmonedas-sfs
spec:
  serviceName: "bdmonedas-servicio"
  replicas: 1
  selector:
    matchLabels:
      app: bdmonedas 
  template:
    metadata:
      labels:
        app: bdmonedas
    spec:
      containers:
        - name: bdmonedas
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_BD
              value: monedas
            - name: POSTGRES_USUARIO
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bdmonedas-secretos
                  key: BDMONEDAS_PASSWORD
          volumeMounts:
            - name: storage-bdmonedas
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: storage-bdmonedas
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
